### ISSUE TITLE
TypeError: file() takes at most 3 arguments (4 given)

### ISSUE THREAD

**Issue by hax0rgb** [swisskyrepo/Vulny-Code-Static-Analysis#12]
**Environment Tested:** MacOS Mojave and Kali Linux 2019.3

The script is giving me the following error when I am trying to run it. Running the same command as shown on your readme file.

<img width="933" alt="Screenshot 2019-11-14 at 1 58 05 AM" src="https://user-images.githubusercontent.com/13043764/68801575-5a605800-0682-11ea-875a-4092271788b7.png">

**Comment by swisskyrepo** [comment]
Use Python 3 ;)
